name: Build XIVLauncher
on: [push, pull_request]
concurrency: build_xl

jobs:
  build-release:
    name: Build Release on Windows
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-2022
    permissions:
      id-token: write
      contents: write # Must be 'write' to create a release
      attestations: write
    steps:
      #      - uses: nadock/verified_commits_check@f9b330e987c2e7121dfc0230e65cb5751ee5fac9
      - uses: actions/checkout@v1
      - name: Initialize Submodules
        run: git submodule update --init --recursive
      - name: Restore Nuget Packages
        run: |
          cd .\src\
          dotnet restore
          cd ..
      - name: Define VERSION
        run: |
          $env:COMMIT = $env:GITHUB_SHA.Substring(0, 7)
          $env:REPO_NAME = $env:GITHUB_REPOSITORY -replace '.*/'
          $env:BRANCH = $env:GITHUB_REF -replace '.*/'

          ($env:REPO_NAME) >> VERSION
          ($env:BRANCH) >> VERSION
          ($env:COMMIT) >> VERSION
      - name: Build Release
        run: |
          cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\src\XIVLauncher.sln /t:Build /p:Configuration=Release
      - name: Generate Hashes File
        run: .\scripts\CreateHashList.ps1 .\src\bin
      - name: Attest Artifacts
        if: ${{ github.repository_owner == 'ottercorp' && github.event_name == 'push' }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            src/bin/XIVLauncher.exe
            src/bin/XIVLauncher.*.dll
            src/bin/XIVLauncher.*.exe
            src/bin/hashes.json
      - name: Velopack Upload
        id: velopack
        env:
          S3AccessKeyID: ${{ secrets.S3AccessKeyID }}
          S3AccessKeySecret: ${{ secrets.S3AccessKeySecret }}
        run: |
          $refver = $env:GITHUB_REF -replace '.*/'
          echo "::set-output name=version::$refver"

          cd src\
          mkdir Releases
          dotnet tool install -g vpk
          vpk download s3 --bucket MyApp --region us-west-1 --keyId $env:S3AccessKeyID --secret $env:S3AccessKeySecret
          vpk pack -u XIVLauncherCN -v $refver -p .\bin -o .\Releases -e XIVLauncherCN.exe --packAuthors OtterCorp --releaseNotes .\XIVLauncher\Resources\CHANGELOG.txt --icon .\XIVLauncher\Resources\dalamud_icon.ico --splashImage .\XIVLauncher\Resources\logo.png --framework net8.0-x64-desktop

          Expand-Archive -Path ".\Releases\XIVLauncherCN-win-Portable.zip" -DestinationPath .\Releases\scratch -Force
          7z a .\Releases\XIVLauncherCN-win-Portable.7z .\Releases\scratch\* -t7z -mx=9

          $json = Get-Content -Raw .\Releases\assets.win.json | ConvertFrom-Json
          for ($i = 0; $i -lt $json.Files.Count; $i++) {
          $json.Files[$i] = $json.Files[$i] -replace 'zip','7z'
          }
          $content = $json | ConvertTo-Json
          set-content -Path .\Releases\assets.win.json -Value $content

          vpk upload s3 --bucket MyApp --region us-west-1 --keyId $env:S3AccessKeyID --secret $env:S3AccessKeySecret
      - name: Attest Setup
        if: ${{ github.repository_owner == 'ottercorp' && github.event_name == 'push' }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            src/Releases/*.exe
            src/Releases/*.nupkg
            src/Releases/*.json
            src/Releases/*.7z
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@a3f74cfd584b0658320aec5e94ab6a8d16dca05f
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            ./src/Releases/*.exe
            ./src/Releases/*.7z

  build:
    name: Build on Windows
    runs-on: windows-2022
    if: "!startsWith(github.ref, 'refs/tags/')"
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@v1
      - name: Initialize Submodules
        run: git submodule update --init --recursive

      - name: Restore Nuget Packages
        run: |
          cd .\src\
          dotnet restore
          cd ..
      - name: Define VERSION
        run: |
          $env:COMMIT = $env:GITHUB_SHA.Substring(0, 7)
          $env:REPO_NAME = $env:GITHUB_REPOSITORY -replace '.*/'
          $env:BRANCH = $env:GITHUB_REF -replace '.*/'

          ($env:REPO_NAME) >> VERSION
          ($env:BRANCH) >> VERSION
          ($env:COMMIT) >> VERSION
      - name: Build
        run: |
          cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\src\XIVLauncher.sln /t:Build /p:Configuration=ReleaseNoUpdate
      - name: Generate Hashes File
        run: .\scripts\CreateHashList.ps1 .\src\bin
      - name: Attest Artifacts
        if: ${{ github.repository_owner == 'ottercorp' && github.event_name == 'push' }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            src/bin/XIVLauncher.exe
            src/bin/XIVLauncher.*.dll
            src/bin/XIVLauncher.*.exe
            src/bin/hashes.json
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: xivlauncher-artifact
          path: src\bin\
